const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const store={get:(k,d)=>JSON.parse(localStorage.getItem(k)||JSON.stringify(d)),set:(k,v)=>localStorage.setItem(k,JSON.stringify(v))};
let foods=store.get('foods',[]), week=store.get('week',{}), guests=store.get('guests',[]), plans=store.get('ramadan',{}), whatsapp=store.get('whatsapp',''), current='home';
const names=['الأحد','الاثنين','الثلاثاء','الأربعاء','الخميس','الجمعة','السبت'];
let installPrompt;
window.addEventListener('beforeinstallprompt', event=>{event.preventDefault();installPrompt=event;$('#installBtn').classList.remove('hidden')});
$('#installBtn').onclick=async()=>{if(!installPrompt)return;installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;$('#installBtn').classList.add('hidden')};
window.addEventListener('appinstalled',()=>$('#installBtn').classList.add('hidden'));
setTimeout(()=>{$('#splash').classList.add('hidden');$('#app').classList.remove('hidden')},3000);
function go(id){current=id;$$('.view').forEach(v=>v.classList.remove('active'));$('#'+id).classList.add('active');$('#pageTitle').textContent=({home:'هناكل إيه؟',foods:'أكلاتي',week:'خطة الأسبوع',ramadan:'خطة رمضان',guests:'عندي عزومة'})[id];$('#backBtn').classList.toggle('hidden',id==='home');if(id==='foods')renderFoods();if(id==='week')renderWeek();if(id==='ramadan')renderRamadan();if(id==='guests')renderGuests()}
$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));$('#backBtn').onclick=()=>go('home');$('#settingsBtn').onclick=whatsappSettings;
function modal(html){$('#modalContent').innerHTML=html;$('#modal').classList.remove('hidden');$('#modal').onclick=e=>{if(e.target===$('#modal'))closeModal()}}
function closeModal(){$('#modal').classList.add('hidden')}
function whatsappSettings(){modal(`<h2>رقم واتساب</h2><p>سيُستخدم هذا الرقم عند إرسال قوائم المشتريات.</p><label class="field">رقم واتساب مع كود الدولة<input id="whatsappNumber" inputmode="tel" value="${whatsapp}" placeholder="مثال: 201012345678"></label><div class="modal-actions"><button class="primary" id="saveWhatsapp">حفظ الرقم</button><button class="secondary" onclick="closeModal()">إلغاء</button></div>`);$('#saveWhatsapp').onclick=()=>{let number=$('#whatsappNumber').value.replace(/[^0-9]/g,'');if(number.length<7){alert('اكتبي رقم واتساب صحيحًا مع كود الدولة.');return}whatsapp=number;store.set('whatsapp',whatsapp);closeModal()}}
function sendWhatsapp(message){if(!whatsapp){whatsappSettings();return}window.open(`https://wa.me/${whatsapp}?text=${encodeURIComponent(message)}`,'_blank')}
function foodOptions(selected=''){return `<option value="">اختاري أكلة</option>${foods.map(f=>`<option ${f.name===selected?'selected':''}>${f.name}</option>`).join('')}`}
function renderFoods(){$('#foodList').innerHTML=foods.length?foods.map((f,i)=>`<article class="food-item"><div class="food-icon">🍲</div><div><h3>${f.name}</h3><p>${f.components.length?f.components.map(x=>x.name).join('، '):'بدون مكونات بعد'}</p></div><div class="item-actions"><button class="round-btn" onclick="foodDetails(${i})">⌕</button><button class="round-btn" onclick="removeFood(${i})">×</button></div></article>`).join(''):'<div class="empty">لسه ما أضفتيش أكلات.<br>ابدئي بأول أكلة بتحبوها في البيت 🤍</div>'}
$('#addFoodBtn').onclick=()=>foodForm();
function foodForm(){modal(`<h2>ضيفي أكلة</h2><label class="field">اسم الأكلة<input id="foodName" placeholder="مثال: صينية بطاطس بالفراخ"></label><label class="field">المكونات (كل مكوّن في سطر)<textarea id="foodComponents" placeholder="بطاطس\nفراخ\nبصل\nصلصة طماطم"></textarea></label><div class="modal-actions"><button class="primary" id="saveFood">حفظ الأكلة</button><button class="secondary" onclick="closeModal()">إلغاء</button></div>`);$('#saveFood').onclick=()=>{let name=$('#foodName').value.trim(),components=$('#foodComponents').value.split('\n').map(name=>({name:name.trim(),needed:true})).filter(x=>x.name);if(!name)return;foods.push({name,components});store.set('foods',foods);closeModal();renderFoods()}}
function foodDetails(i){let f=foods[i];modal(`<h2>${f.name}</h2><p>علمي فقط على الأشياء الناقصة.</p><div>${f.components.length?f.components.map((c,j)=>`<div class="component-row"><input id="c${j}" type="checkbox" ${c.needed?'checked':''}><span>${c.name}</span></div>`).join(''):'<div class="empty">لا توجد مكونات.</div>'}</div><div class="modal-actions"><button class="primary" id="shareFood">إرسال الناقص لواتساب</button><button class="secondary" id="editComponents">تعديل المكونات</button><button class="secondary" onclick="closeModal()">إغلاق</button></div>`);$('#shareFood').onclick=()=>{let missing=f.components.filter((c,j)=>$('#c'+j).checked).map(c=>'• '+c.name).join('\n')||'لا توجد طلبات';sendWhatsapp(`طلبات ${f.name}:\n${missing}`)};$('#editComponents').onclick=()=>componentEditor(i)}
function componentEditor(i){let f=foods[i];modal(`<h2>تعديل مكونات ${f.name}</h2><p>اكتبي كل مكوّن في سطر. يمكنكِ الإضافة أو الحذف أو التعديل.</p><label class="field">المكونات<textarea id="editedComponents">${f.components.map(c=>c.name).join('\n')}</textarea></label><div class="modal-actions"><button class="primary" id="saveComponents">حفظ التعديل</button><button class="secondary" onclick="foodDetails(${i})">رجوع</button></div>`);$('#saveComponents').onclick=()=>{let updated=$('#editedComponents').value.split('\n').map(name=>name.trim()).filter(Boolean);f.components=updated.map(name=>({name,needed:true}));store.set('foods',foods);closeModal();renderFoods()}}
function removeFood(i){let f=foods[i];modal(`<h2>حذف الأكلة؟</h2><p>هل أنتِ متأكدة من حذف «${f.name}»؟ لن يمكن استرجاعها بعد الحذف.</p><div class="modal-actions"><button class="primary" id="confirmDelete">نعم، احذفيها</button><button class="secondary" onclick="closeModal()">إلغاء</button></div>`);$('#confirmDelete').onclick=()=>{foods.splice(i,1);store.set('foods',foods);closeModal();renderFoods()}}
function renderWeek(){let start=new Date();start.setDate(start.getDate()-start.getDay());$('#weekGrid').innerHTML=names.map((n,i)=>{let d=new Date(start);d.setDate(start.getDate()+i);let key=d.toISOString().slice(0,10);return `<div class="day-card"><b>${n}<br><small>${d.getDate()}/${d.getMonth()+1}</small></b><select data-week="${key}">${foodOptions(week[key])}</select></div>`}).join('')}
$('#saveWeekBtn').onclick=()=>{$$('[data-week]').forEach(s=>week[s.dataset.week]=s.value);store.set('week',week);alert('تم حفظ خطة الأسبوع 🤍')};$('#weekShopBtn').onclick=()=>shopping($$('[data-week]').map(s=>s.value).filter(Boolean),'الأسبوع');
function shopping(foodNames,title){let all=foodNames.flatMap(n=>(foods.find(f=>f.name===n)?.components||[]).map(c=>c.name));let unique=[...new Set(all)];modal(`<h2>قائمة مشتريات ${title}</h2><p>علمي على الأشياء الناقصة ثم أرسليها.</p>${unique.map((n,i)=>`<div class="component-row"><input id="s${i}" type="checkbox" checked><span>${n}</span></div>`).join('')||'<div class="empty">اختاري أكلات أولًا.</div>'}<div class="modal-actions"><button class="primary" id="shareShop">إرسال لواتساب</button><button class="secondary" onclick="closeModal()">إغلاق</button></div>`);$('#shareShop').onclick=()=>{let m=unique.filter((_,i)=>$('#s'+i).checked).map(x=>'• '+x).join('\n')||'لا توجد طلبات';sendWhatsapp(`قائمة مشتريات ${title}:\n${m}`)}}
function renderRamadan(){let inp=$('#ramadanMonth');if(!inp.value)inp.value=new Date().toISOString().slice(0,7);let [y,m]=inp.value.split('-').map(Number),days=new Date(y,m,0).getDate();$('#ramadanGrid').innerHTML=Array.from({length:days},(_,i)=>{let key=`${y}-${String(m).padStart(2,'0')}-${String(i+1).padStart(2,'0')}`;return `<button class="date-btn ${plans[key]?'has-plan':''}" onclick="ramadanDay('${key}')">${i+1}</button>`}).join('')};$('#ramadanMonth').onchange=renderRamadan;
function ramadanDay(key){let p=plans[key]||{};modal(`<h2>${key}</h2><div class="meal-sections">${[['سحور','suhoor'],['فطار','iftar'],['حلو','dessert'],['عصير','juice']].map(([l,k])=>`<label class="meal-section"><b>${l}</b><select id="${k}">${foodOptions(p[k])}</select></label>`).join('')}</div><div class="modal-actions"><button class="primary" id="saveRamadan">حفظ اليوم</button><button class="secondary" onclick="closeModal()">إلغاء</button></div>`);$('#saveRamadan').onclick=()=>{plans[key]={suhoor:$('#suhoor').value,iftar:$('#iftar').value,dessert:$('#dessert').value,juice:$('#juice').value};store.set('ramadan',plans);closeModal();renderRamadan()}}
function renderGuests(){$('#guestList').innerHTML=guests.length?guests.map((g,i)=>`<article class="guest-item"><h3>${g.name}</h3><p>${g.date||'بدون تاريخ'} · ${g.foods.filter(Boolean).join('، ')||'لم تُختَر أصناف بعد'}</p><div class="item-actions"><button class="round-btn" onclick="guestDetails(${i})">⌕</button></div></article>`).join(''):'<div class="empty">أول عزومة محتاجة خطة جميلة ✨</div>'}
$('#newGuestBtn').onclick=()=>guestForm();function guestForm(){modal(`<h2>خطة عزومة</h2><label class="field">اسم المناسبة<input id="guestName" placeholder="مثال: عزومة الجمعة"></label><label class="field">التاريخ<input id="guestDate" type="date"></label><div class="meal-sections">${[['مقبلات','app'],['الطبق الرئيسي','main'],['سلطات','salad'],['حلو','dessert'],['مشروبات','drink']].map(([l,k])=>`<label class="meal-section"><b>${l}</b><select id="g${k}">${foodOptions()}</select></label>`).join('')}</div><div class="modal-actions"><button class="primary" id="saveGuest">حفظ العزومة</button><button class="secondary" onclick="closeModal()">إلغاء</button></div>`);$('#saveGuest').onclick=()=>{let name=$('#guestName').value.trim()||'عزومة جديدة';guests.push({name,date:$('#guestDate').value,foods:['app','main','salad','dessert','drink'].map(k=>$('#g'+k).value)});store.set('guests',guests);closeModal();renderGuests()}}
function guestDetails(i){let g=guests[i];shopping(g.foods.filter(Boolean),g.name)}
